#pragma once

#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_MAJOR 1
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_MINOR 2
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_PATCH 0
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_BUILD 0
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_TEXT "1.2"
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_WTEXT L"1.2"
