#pragma once

#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_MAJOR 1
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_MINOR 0
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_PATCH 0
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_BUILD 0
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_TEXT "1.0"
#define TRAFFICMONITOR_QUOTA_PLUGIN_VERSION_WTEXT L"1.0"
